package edu.sjsu.cmpe.kidsontrack.domain;

import javax.xml.bind.annotation.XmlRootElement;

import org.springframework.data.mongodb.core.mapping.Document;

@Document
@XmlRootElement(name = "students")
public class Student extends User{

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * This is the sequtial student Id generated by Kids On Track Application.
	 */
	//private long studentId;



	

}
